# Generated by Django 3.2.7 on 2021-09-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('role', models.TextField()),
                ('desc', models.CharField(max_length=300)),
                ('salary', models.CharField(max_length=30)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
