# Generated by Django 3.2.7 on 2021-09-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='jobs',
            name='desc',
            field=models.TextField(),
        ),
    ]
