# Generated by Django 3.2.7 on 2021-09-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0004_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('nationality', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('qualifications', models.TextField()),
                ('cv', models.FileField(upload_to='')),
            ],
        ),
    ]
